# Generated by Django 3.0 on 2021-09-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('customer_xid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='0', max_length=10)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.WalletUser')),
            ],
        ),
        migrations.CreateModel(
            name='Koran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reference_id', models.CharField(max_length=32)),
                ('deposit_by', models.CharField(blank=True, max_length=128)),
                ('deposit_at', models.DateTimeField()),
                ('withdrawal_by', models.CharField(blank=True, max_length=128)),
                ('withdrawal_at', models.DateTimeField()),
                ('balance', models.IntegerField()),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.Wallet')),
            ],
        ),
    ]
